### ISSUE TITLE
some training&inference question

### ISSUE THREAD

**Issue by DonkeyHang** [yuval-reshef/StreamVC#4]
hi there,

Could you told me what pretrained model should download when i want to training this projects.

and In the readme, `The streaming infernce isn't fully implemented at the moment.`, 
so now, can i used this repo to inference correctly?

thank you
@yuval-reshef @yonicohen96

**Comment by yuval-reshef** [comment]
Hi @DonkeyHang,
I'm not sure I understand the question.
Currently there is no pre-trained model, so training would have to start from scratch.
With a trained model, inference can be done just fine with the inference script, just not in "streaming" mode.

**Comment by DonkeyHang** [comment]
> Hi @DonkeyHang, I'm not sure I understand the question. Currently there is no pre-trained model, so training would have to start from scratch. With a trained model, inference can be done just fine with the inference script, just not in "streaming" mode.

thanks for reply,

ok, so if i want to train this model, so i can used preprocessing_dataset module and training it right?

So will you continue to work on streaming mode related tasks in the future?

**Comment by yuval-reshef** [comment]
I would currently recommend to use the code in the main branch since it is tested and documented a bit better.
the changes in the `preprocessing_dataset` are a work in progress and will be eventually merged to the main branch.

About the streaming mode, I'm not currently working on adding that, but I might in the future.

**Comment by DonkeyHang** [comment]
thank you for your reply
